modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="autosow"
version="2.0.0"
displayName="Auto Sow"
authors="Neni-o"
description='''
Right-click a mature crop with its corresponding item to auto-harvest and instantly replant.
Also works with dispensers (when enabled) for automated harvesting of most supported plants.

Supported plants:

    🌾 Wheat

    🥕 Carrots

    🥔 Potatoes

    🍠 Beetroots

    🌸 Torchflower

    🔥 Nether Wart

    🍫 Cocoa

    🍈 Melon (shears in dispenser — drops slices or whole melon depending on config)

    🎃 Pumpkin (shears in dispenser — always drops whole pumpkin)

    🍒 Sweet Berries (shears in dispenser — berry amount depends on bush age)

Extra features:

    Optional direct-to-inventory collection for harvested items.

    Configurable seed/item consumption on replant.

    Dispenser support can be toggled on/off in config.

    Sweet berry bushes can be harvested at age 1–3, with berry count based on maturity.
'''

# (opcjonalnie) minimalna wersja Javy
[mods.features]
java_version="[21,)"
